GET http://127.0.0.1:8000/api/users

####################################

POST http://127.0.0.1:8000/api/users

{
    "first_name": "Tinnakorn",
    "last_name": "Choompee",
    "email": "tinnakorn@gmail.com",
    "password": 123456
}

####################################

PUT http://127.0.0.1:8000/api/users/21

{
    "first_name": "BellNajA",
    "last_name": "Eiri",
    "email": "admin@gmail.com",
    "password": 123456
}

####################################

DELETE  http://127.0.0.1:8000/api/users/21
