@name = orders
@id = 1

GET {{host}}/{{name}}
Authorization: {{token}}

####################################

GET {{host}}/{{name}}/{{id}}
Authorization: {{token}}

####################################