@name = roles
@id = 1

GET {{host}}/{{name}}
Authorization: {{token}}

####################################

POST {{host}}/{{name}}
Authorization: {{token}}

{
    "name": "Test Role"
}

####################################

PUT {{host}}/{{name}}/{{id}}
Authorization: {{token}}

{
    "name": "Role Update"
}


####################################

DELETE  {{host}}/{{name}}/{{id}}
Authorization: {{token}}