@name = roles
@id = 5

GET {{host}}/{{name}}
Authorization: {{token}}

####################################

POST {{host}}/{{name}}
Authorization: {{token}}

{
    "name": "Custom",
    "permissions": [1, 2, 5, 6]
}

####################################

PUT {{host}}/{{name}}/{{id}}
Authorization: {{token}}

{
    "name": "Custom Update",
    "permissions": [1]
}


####################################

DELETE  {{host}}/{{name}}/{{id}}
Authorization: {{token}}