@name = users
@id = 1

POST {{host}}/register

{
    "first_name": "Tinnakorn",
    "last_name": "Choompee",
    "email": "tinnakorn@gmail.com",
    "password": "password",
    "password_confirmation": "password",
    "role_id": "1"
}

####################################

POST {{host}}/login

{
    "email": "tinnakorn@gmail.com",
    "password": "password"
}

####################################

GET {{host}}/auth/profile
Authorization: {{token}}

####################################

GET {{host}}/{{name}}
Authorization: {{token}}

####################################

GET {{host}}/{{name}}/{{id}}
Authorization: {{token}}

####################################

POST {{host}}/{{name}}
Authorization: {{token}}

{
    "first_name": "Tinnakorn",
    "last_name": "Choompee",
    "email": "tinnakorn@gmail.com",
    "password": "password"
}

####################################

PUT {{host}}/{{name}}/{{id}}
Authorization: {{token}}

{
    "first_name": "Tinnakorn",
    "last_name": "Choompee",
    "email": "tinnakorn@gmail.com",
    "password": 123456
}

####################################

DELETE  {{host}}/{{name}}/{{id}}
Authorization: {{token}}
